/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package testjdbc

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.postgresql.ds.PGSimpleDataSource
import java.io.PrintWriter
import java.sql.DriverManager
import java.sql.SQLException
import java.util.logging.Level
import java.util.logging.Logger

class Library {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {

            DriverManager.setLogWriter(PrintWriter(System.out, true))

            val host = "hostname"
            val username = "user"
            val password = "password"
            val db = "dbname"
            val url = "jdbc:postgresql://$host/$db?user=$username&password=$password"

            Logger.getLogger("").level = Level.FINE
            Logger.getLogger("").handlers[0].level = Level.FINE
            val logger = Logger.getLogger("wombat")

            val psqlDs = PGSimpleDataSource()
            psqlDs.setUrl(url)
            psqlDs.ssl = false
            psqlDs.sslMode = "disable"
            val config = HikariConfig()
            config.dataSource = psqlDs

            logger.fine("Trying to connect to PostgreSQL database $url")
            val ds = HikariDataSource(config)

            try {
                val conn = ds.connection

                val st = conn.prepareStatement("SELECT 1")
                val rs = st.executeQuery()
                while (rs.next()) {
                    logger.info("Column 1 returned: " + rs.getString(1))
                }
                rs.close()
                st.close()

                conn.close()

                ds.close()
            } catch (e: SQLException) {
                e.printStackTrace(System.out)
            }
        }
    }

    fun someLibraryMethod(): Boolean {
        return true
    }
}
